# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
    ]
