# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170523_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_label',
            field=models.CharField(max_length=100, unique='True'),
        ),
    ]
